### PR TITLE
Update docs, refactor tests & publishing tweaks

### PR DESCRIPTION
**Pull request by vladimyr**
**What is the purpose of this pull request? (put an "X" next to item)**

- [x] Documentation update
- [x] Bug fix
- [ ]  New feature
- [x] Other, please explain:

**What changes did you make? (Give an overview)**

1. Converted actual config from json file to common js module so it can be used to lint test suite which got updated/refactored. 
2. Altered publishing settings to make sure that only necessary files end up in resulting tarball (by adding `files` field to `package.json`).
3. Uptated docs to mention `install-peerdeps` as easier installation method.
4. Added `.editorconfig`.

**Is there anything you'd like reviewers to focus on?**

This also bumps `eslint-config-semistandard` peer dep requirement as reported #29 

<hr>

@feross  @Flet Is there any reason why I'm removed as a contributor to this repo/package?
I understand that ownership has been transferred to @standard organization which I'm not a member of but that situation could be solved politely by either invitation or prior email notice before removing my commit access?
Don't get me wrong I'm perfectly fine to continue contributing from outside I'm just voicing my dissatisfaction with how things were handled.

### CODE REVIEW

**Comment by vladimyr** [comment]
/ping @standard

Is anyone out there having some spare time to review & potentially merge this one?

**Comment by Flet** [comment]
Sorry for the delays. Thanks!

**Comment by Flet** [comment]
Unsure why you were not invited to the standard org. I've corrected this! Thanks again for helping out!

**Comment by Flet** [comment]
published as `eslint-config-semistandard@15.0.1`

**Comment by feross** [comment]
The change to using semicolons, etc. in this package breaks the tests in `standard` since this was included in the test suite. I guess it makes sense to follow the semistandard style guide in this package, so I'll just remove this package from the test suite.

**Pull request merged**
